# Generated by Django 5.1.2 on 2024-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
