# Generated by Django 5.1.2 on 2024-11-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_customuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
